channels:
  - conda-forge
dependencies:
  - apbs
  - biopython
  - speleo3::csb
  - coverage
  - sbl::dssp
  - mdtraj
  - msms
  - pip
  - pymol-open-source
  - pytest
  - ruff
  - scipy
  - kimlab::stride
  - speleo3::tmalign
