name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: ci

    - name: Activate environment
      run: echo "$MAMBA_ROOT_PREFIX/envs/ci/bin" >> $GITHUB_PATH

    - name: Install
      run: python3 -m pip install -q .

    - name: Test
      run: |
        python3 -m coverage run -m pytest
        python3 -m coverage xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Lint
      run: ruff check psico tests

    - name: Type checking
      run: mypy
